// <auto-generated />
namespace Goblinary.CharacterData.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201508110456429_AddSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
